config/routes.rb
Rails.application.routes.draw do

  root 'gossips#index'

  resources :gossips
  resources :sessions
  resources :comments
  resources :cities, only: [:show]
  resources :users, only: [:new, :create, :show]


  get 'home/', to: 'static_pages#home'
  get 'home/:first_name', to: 'static_pages#home'
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    
    has_many :users
    
    validates :name,
    presence: true,
    uniqueness: true,
    length: {in: 3..30}
    
end

app/models/comment.rb
class Comment < ApplicationRecord

    belongs_to :user
    belongs_to :gossip

end

app/models/gossip.rb
class Gossip < ApplicationRecord

    belongs_to :user
    has_many :tag_lists
    has_many :tags, through: :tag_lists
    has_many :comments
    has_many :likes

end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :gossip, optional: true
    belongs_to :comment, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender,  class_name: "User"
    belongs_to :recipient,  class_name: "User"
    has_many :users, through: :recipients
    
    validates :content,
               presence: true,
               length: {in: 3..300}
end

app/models/recipient.rb
class Recipient < ApplicationRecord
    belongs_to :private_message
    belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :tag_lists
    has_many :gossips, through: :tag_lists
    
    validates :title, length: {in: 3..14}

end

app/models/tag_list.rb
class TagList < ApplicationRecord
    belongs_to :gossip
    belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord

belongs_to :city
has_many :gossips
has_many :comments
has_many :gossips_likes
has_many :comments_likes
validates :email, uniqueness: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def new
    @city = City.new

  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
      @cities = City.all
  end

  def show

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(gossip_id: params[:gossip], content: params[:content],  user: current_user)
   if @comment.save
     flash[:success] = "The commentaire was succesfully saved !"
     redirect_to gossip_path(@comment.gossip.id)
   else
     messages = []
     if @comment.errors.any?
         @comment.errors.full_messages.each do |message|
         messages << message
       end
       flash.now[:error] = "Tu t'es trompé poulet, la liste des erreurs est :#{messages.join(" ")}"
     end
     render 'new'
   end
  end

  def update
    @comment = Comment.find(params[:id])
   # Condition pour définir si l'utilisateur connecté à la session est celui qui a écrit le commentaire
   if !current_user?(@comment.user)
     flash[:error] = "Vous n'êtes pas le bon utilisateur."
     redirect_to gossips_path
   else
     if @comment.update(comment_params)
       flash[:success] = "Ton super comment a correctement été mis à jour !"
       redirect_to gossip_path(@comment.gossip.id)
     else
       render 'edit'
     end
   end


  end

  def edit
    @comment = Comment.find(params[:id])
    # Condition pour définir si l'utilisateur connecté à la session est celui qui a écrit le commentaire
    if !current_user?(@comment.user)
      flash[:error] = "Vous n'êtes pas le bon utilisateur."
      redirect_to gossips_path
    end

  end

  def destroy
    @comment = Comment.find(params[:id])
    # Condition pour définir si l'utilisateur connecté à la session est celui qui a écrit le commentaire
    if !current_user?(@comment.user)
      flash[:error] = "Vous n'êtes pas le bon utilisateur."
      redirect_to gossips_path
    else
      if @comment.destroy
      flash[:success] = "Ton commentaire de comère de luxe a été correctement destroy!"
        redirect_to gossip_path(@comment.gossip.id)
      else
        render 'edit'
      end
    end

  end

  def index
    @comments = Comment.all
  end

  def show
    @comment = @gossip.comments.all
    @comment = @gossip.comments.build
    @comment = Comment.find(params[:id])
  end
  private
  def comment_params
    params.require(:comment).permit(:content)
  end

  def authenticate_user
    unless current_user
      flash[:error] = "Vous devez vous connecter pour accéder au contenu."
      redirect_to new_session_path
    end
  end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def index
  end

  def show
    @gossip = Gossip.find(params[:id])

  end

  def new
    @gossip = Gossip.new
  end


  def create
     @gossip = Gossip.new(title: params[:title],
       content: params[:content],  user: User.find(params[:user]))
       if @gossip.save
         flash[:success] = "The Gossip was successfuly created"
           redirect_to gossips_path
       else render 'new'
  end
end

def edit
    @gossip = Gossip.find(params[:id])
end

def update
    @gossip = Gossip.find(params[:id])
    gossip_params =  params.require(:gossip).permit(:title, :content, :user)
    if @gossip.update(gossip_params)
      flash[:success] = "The Gossip was successfuly updated"
    redirect_to gossips_path
  end
end

def destroy
  @gossip = Gossip.find(params[:id])
@gossip.destroy
redirect_to gossips_path
end


private

def gossip_params
    return params.require(:gossip).permit(:title, :content, :user)
end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:email, :password)
    @user = User.new(user_params)
    if @user.valid?

    else render 'new'

  end
end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
        @user = params[:first_name]
      end
    
      def team
      end
    
      def contact
      end
    
      def gossip
        @gossips = Gossip.find(params[:gossip_id])
      end
    
      def gossips
        @gossips = Gossip.all
        render :layout => nil

      end 
    
    
      def user
        @user = User.find(params[:user_id])
        @gossips_user = Gossip.where(user: @user)
      end 
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:email, :password, :username)
    @user = User.new(user_params)
    if @user.valid?

    else render 'new'

  end
end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/index.html.erb
<h1>Cities#index</h1>
<p>Find me in app/views/cities/index.html.erb</p>

app/views/cities/show.html.erb
<head>
  <style>
    <title>The Gossip Project</title>
    <style>
    h1, p {
     margin-top: 30px;
     margin-left: 30px;
    }
    body{
    background: #eee;
    }

    span{
    font-size:15px;
    }

    a{
    text-decoration:none;
    color: #0062cc;
    }
    .box{
    padding:60px 0px;
    }
    .box-part{
    background:#FFF;
    border-radius:0;
    padding:30px 10px;
    margin:30px 0px;
    }
    .text{
    margin:20px 0px;
    }

    .fa{
    color:#6d6875;
    }
    </style>
<!-- Title -->

  <div class="container text-center">
    <h1 class="my-4"> Welcome to <%= City.find(params[:id]).name %></h1>
    <!-- Title  -->
    <div class="box">
        <div class="container">
         	<div class="row">
            <% Gossip.all.select { |gossip| gossip.user.city.id == City.find(params[:id]).id }.each do |gossip| %>
            <div class="col-md-6 col-sm-4">

            <div class="box-part text-center">
            <i class="fa fa-user-o fa-3x" aria-hidden="true"></i>
               <br>
               <br>
              <div class="title">
                <h4><%= gossip.title %></h4>
                <span><%= gossip.content %></span>
              </div>
              <div class="row justify-content-center">
                <div class="col-6">
         <h6 class="card-subtitle m-3 text-muted">Gossip n°<%= gossip.id %>, de <%= link_to gossip.user.first_name, user_path(gossip.user.id)%></h6>
         <a class="btn btn-secondary" <%= link_to "See the gossip", gossip_path(gossip.id), :class => "card-link"%>
      </div>
    </div>
  </div>
 </div>
<% end %>

</div>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/gossips/edit.html.erb
<br></br>
<h1 class="text-center"> Edit your Gossip here</h1>
<br></br>


<div class="row justify-content-center">
  <div class="col-6">

  <%= form_for @gossip do |f| %>
  <div class ="form-group">
    <label> Title to edit: </label>
    <%= f.text_field :title, class: 'form-control'%>
    </div>

    <div class ="form-group">
      <label> Content to edit: </label>
      <%= f.text_area :content, class: 'form-control'%>
      </div>

      <div class ="form-group">
         <button type="submit" class ="btn btn-primary"> Edit </button>
         </div>

        </div>
        </div>

        <% end%>

app/views/gossips/index.html.erb
<head>

    <title>The Gossip Project</title>
    <style>
    h1, p {
     margin-top: 30px;
     margin-left: 30px;
    }


    body{
    background: #eee;
    }

    span{
    font-size:15px;
    }

    a{
    text-decoration:none;
    color: #0062cc;
    }
    .box{
    padding:60px 0px;
    }

    .box-part{
    background:#FFF;
    border-radius:0;
    padding:30px 10px;
    margin:30px 0px;
    }
    .text{
    margin:20px 0px;
    }

    .fa{
    color:#6d6875;
    }
    </style>

    <div class="jumbotron jumbotron-fluid JumboHeaderImg">
      <div class="container">
        <h1 class="display-4 text-center"> Welcome <%= params['first_name']%>! 🕵🏻‍♀️ </h1>
        <p class="text-center">Do you want to create your Gossip? Submit it by clicking on the button below</p>
        <br>
        <div class="container text-center">
        <a href="<%= new_gossip_path%>" class="btn btn-secondary text-center"> Enter your best gossip</a>
        <br>
        </div>
       </div>
    </div>
  </head>

<body>

<div class="box">
    <div class="container">
     	<div class="row">
        	<% Gossip.all.reverse.each do |gossip| %>
          <div class="col-md-6 col-sm-4">

					<div class="box-part text-center">
          <i class="fa fa-user-circle fa-3x" aria-hidden="true"></i>
             <br>
             <br>
						<div class="title">
							<h4><%= gossip.title %></h4>
							<span><%= gossip.content %></span>
						</div>
            <br>
            <div class="row justify-content-center">
              <div class="col-6">
            <a href="/gossips/<%= gossip.id %>" class="btn btn-sm btn-secondary">Gossip</a>
            <br>
            <br>
              <hr>
            <div class="social-meta">
              <span><i class="fa fa-hand-peace-o" aria-hidden="true"></i>   25 likes</span>
              <p><i class="fa fa-commenting-o"></i>   13 comments</p>
            </div>
					 </div>

			  	</div>


		 </div>
    </div>
    <% end %>

  </div>
 </div>
</div>




</body>

app/views/gossips/new.html.erb
<% if @gossip.errors.any? %>

<div class="alert alert-danger" role="alert">
  <p>  Sorry, your super gossip cannot be created because of the following: </p>
    <ul>
      <% @gossip.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>



<br></br>
<h1 class="text-center"> Enter your Gossip here</h1>
<br></br>


<div class="row justify-content-center">
  <div class="col-6">

    <%=form_tag url_for(action: 'create'), method: "post" do %>

      <%= label_tag 'Title', nil, :class =>"" %>
      <%= text_field_tag 'title', @gossip.title, :class => "form-control" %>
      <br>
      <%= label_tag 'Content', nil, :class =>"" %>
      <%= text_area_tag 'content', @gossip.content, :class => "form-control" %>
      <br>
      <%= label_tag 'Author', nil, :class =>"" %>
      <%= select_tag 'user', options_from_collection_for_select(User.all, :id, :first_name), :class => "form-control", prompt: 'choose the user' %>
      <br>
      <div class="row justify-content-center">
      <%= submit_tag "Submit my gossip 🤙🏼", :class => "btn btn-secondary btn-lg" %>
</div>
      <% end %>
  </div>
</div>

app/views/gossips/show.html.erb
<div class="container">
<div class="row justify-content-center">
  <!-- Gossip  -->

  <div class="card w-25">
    <div class="card">
      <img class="card-img-top" alt="Card image cap" src="https://www.omnycontent.com/d/clips/aaea4e69-af51-495e-afc9-a9760146922b/93442535-ff58-4499-9697-aa3200e14c00/cd61a241-32d6-49cd-9670-aa3200e17784/image.jpg?t=1555508456&size=Large">
      <div class="card-body">
        <h5 class="card-title"><%=@gossip.title %></h5>
        <p class="card-text"><%= @gossip.content %></p>
        <p class="card-text">
        <p class="card-text">
          <small class="text-muted">Created by <%=link_to Gossip.find(params['id'].to_i).user.first_name, user_path(Gossip.find(params['id'].to_i).user.id) %>
            on <%=@gossip.created_at.strftime("%d/%m/%Y à %H:%I") %>
            in <a href="<%= city_path(@gossip.user.city.id) %>"><%=@gossip.user.city.name %></a>
          </small>
        </p>

        <div class="row justify-content-center">
            <div class="col-sm-6">
              <a href="<%= edit_gossip_path%>" class="btn btn-sm btn-info float-right">Edit</a>
              <div class="row-12 text-center">
              <a href="<%= gossip_path%>" class="btn  btn-sm btn-danger float-left" data-confirm="Are you sure you want to delete this gossip?"
              data-method="DELETE">Delete</a>

                </div>
          </div>
        </div>
      </div>
      <!-- Comments -->

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>Users#destroy</h1>
<p>Find me in app/views/users/destroy.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">
<title>Bootstrap Sign up Form Horizontal</title>
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
<style type="text/css">
	body {
		color: #999;
		background: #f3f3f3;
		font-family: 'Roboto', sans-serif;
	}
    .form-control {
		border-color: #eee;
        min-height: 41px;
		box-shadow: none !important;
	}
    .form-control:focus {
		border-color: #5cd3b4;
	}
    .form-control, .btn {
        border-radius: 3px;
    }
	.signup-form {
		width: 500px;
		margin: 0 auto;
		padding: 30px 0;
	}
    .signup-form h2 {
		color: #333;
        margin: 0 0 30px 0;
		display: inline-block;
		padding: 0 30px 10px 0;
		border-bottom: 3px solid #5cd3b4;
    }
    .signup-form form {
		color: #999;
		border-radius: 3px;
    	margin-bottom: 15px;
        background: #fff;
        box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
        padding: 30px;
    }
	.signup-form .form-group {
		margin-bottom: 20px;
	}
	.signup-form label {
		font-weight: normal;
		font-size: 13px;
	}
    .signup-form input[type="checkbox"] {
		margin-top: 2px;
	}
    .signup-form .btn {
        font-size: 16px;
        font-weight: bold;
		background: #5cd3b4;
		border: none;
		margin-top: 20px;
		min-width: 140px;
    }
	.signup-form .btn:hover, .signup-form .btn:focus {
		background: #b5838d;
        outline: none !important;
	}
    .signup-form a {
		color: #5cd3b4;
		text-decoration: underline;
	}
	.signup-form a:hover {
		text-decoration: none;
	}
    .signup-form form a {
		color: #b5838d;
		text-decoration: none;
	}
	.signup-form form a:hover {
		text-decoration: underline;
	}
</style>
</head>
<body>
<div class="signup-form">
    <form action="/examples/actions/confirmation.php" method="post" class="form-horizontal">
		<div class="col-xs-8 col-xs-offset-4">
			<h2>Sign Up</h2>
		</div>
        <div class="form-group">
			<label class="control-label col-xs-4">Username</label>
			<div class="col-xs-8">
                <input type="text" class="form-control" name="username" required="required">
            </div>
        </div>
		<div class="form-group">
			<label class="control-label col-xs-4">Email Address</label>
			<div class="col-xs-8">
                <input type="email" class="form-control" name="email" required="required">
            </div>
        </div>
		<div class="form-group">
			<label class="control-label col-xs-4">Password</label>
			<div class="col-xs-8">
                <input type="password" class="form-control" name="password" required="required">
            </div>
        </div>
		<div class="form-group">
			<label class="control-label col-xs-4">Confirm Password</label>
			<div class="col-xs-8">
                <input type="password" class="form-control" name="confirm_password" required="required">
            </div>
        </div>
		<div class="form-group">
			<div class="col-xs-8 col-xs-offset-4">
				<p><label class="checkbox-inline"><input type="checkbox" required="required"> I accept the <a href="#">Terms of Use</a> &amp; <a href="#">Privacy Policy</a>.</label></p>
				<button type="submit" class="btn btn-secondary btn-lg">Sign Up</button>
			</div>
		</div>
    </form>
	<div class="text-center">Already have an account? <a href="#">Login here</a></div>
</div>
</body>
</html>

</div>

app/views/users/show.html.erb
<br>
<br>
<div class="container">
  <div class="row justify-content-center">
    <div class="card w-50 p-1">
     <div class="card">
    <div class="card-header text-center"><strong>User profile</strong></div>
     <div class="card-body">
       <p class="card-text"> Name: <%= @user.first_name %>  </p>
       <p class="card-text"> Last name: <%= @user.last_name %>  </p>
       <p class="card-text"> Description: <%= @user.description %> </p>
       <p class="card-text"> Email: <%= @user.email %>  </p>
       <p class="card-text"> Age: <%= @user.age %>  </p>
       <p class="card-text"> City: <a href="/cities/<%= @user.city.id %>"><%= @user.city.name %></a> </p>
    </div>
    <button type="button" class="btn btn-secondary">Edit this profile</button>
   </div>
  </div>
 </div>
</div>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>