config/routes.rb
Rails.application.routes.draw do

  root 'gossips#index'

  resources :gossips
  resources :sessions
  resources :comments
  resources :cities, only: [:show]
  resources :users, only: [:new, :create, :show]


  get 'home/', to: 'static_pages#home'
  get 'home/:first_name', to: 'static_pages#home'
  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    
    has_many :users
    
    validates :name,
    presence: true,
    uniqueness: true,
    length: {in: 3..30}
    
end

app/models/comment.rb
class Comment < ApplicationRecord

    belongs_to :user
    belongs_to :gossip

end

app/models/gossip.rb
class Gossip < ApplicationRecord

    belongs_to :user
    has_many :tag_lists
    has_many :tags, through: :tag_lists
    has_many :comments
    has_many :likes

end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :gossip, optional: true
    belongs_to :comment, optional: true
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
    belongs_to :sender,  class_name: "User"
    belongs_to :recipient,  class_name: "User"
    has_many :users, through: :recipients
    
    validates :content,
               presence: true,
               length: {in: 3..300}
end

app/models/recipient.rb
class Recipient < ApplicationRecord
    belongs_to :private_message
    belongs_to :user
end

app/models/tag.rb
class Tag < ApplicationRecord
    has_many :tag_lists
    has_many :gossips, through: :tag_lists
    
    validates :title, length: {in: 3..14}

end

app/models/tag_list.rb
class TagList < ApplicationRecord
    belongs_to :gossip
    belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord

belongs_to :city
has_many :gossips
has_many :comments
has_many :gossips_likes
has_many :comments_likes
validates :email, uniqueness: true

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def new
    @city = City.new

  end

  def create
  end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
      @cities = City.all
  end

  def show

  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(gossip_id: params[:gossip], content: params[:content],  user: current_user)
   if @comment.save
     flash[:success] = "The commentaire was succesfully saved !"
     redirect_to gossip_path(@comment.gossip.id)
   else
     messages = []
     if @comment.errors.any?
         @comment.errors.full_messages.each do |message|
         messages << message
       end
       flash.now[:error] = "Tu t'es trompé poulet, la liste des erreurs est :#{messages.join(" ")}"
     end
     render 'new'
   end
  end

  def update
    @comment = Comment.find(params[:id])
   # Condition pour définir si l'utilisateur connecté à la session est celui qui a écrit le commentaire
   if !current_user?(@comment.user)
     flash[:error] = "Vous n'êtes pas le bon utilisateur."
     redirect_to gossips_path
   else
     if @comment.update(comment_params)
       flash[:success] = "Ton super comment a correctement été mis à jour !"
       redirect_to gossip_path(@comment.gossip.id)
     else
       render 'edit'
     end
   end


  end

  def edit
    @comment = Comment.find(params[:id])
    # Condition pour définir si l'utilisateur connecté à la session est celui qui a écrit le commentaire
    if !current_user?(@comment.user)
      flash[:error] = "Vous n'êtes pas le bon utilisateur."
      redirect_to gossips_path
    end

  end

  def destroy
    @comment = Comment.find(params[:id])
    # Condition pour définir si l'utilisateur connecté à la session est celui qui a écrit le commentaire
    if !current_user?(@comment.user)
      flash[:error] = "Vous n'êtes pas le bon utilisateur."
      redirect_to gossips_path
    else
      if @comment.destroy
      flash[:success] = "Ton commentaire de comère de luxe a été correctement destroy!"
        redirect_to gossip_path(@comment.gossip.id)
      else
        render 'edit'
      end
    end

  end

  def index
    @comments = Comment.all
  end

  def show
    @comment = @gossip.comments.all
    @comment = @gossip.comments.build
    @comment = Comment.find(params[:id])
  end
  private
  def comment_params
    params.require(:comment).permit(:content)
  end

  def authenticate_user
    unless current_user
      flash[:error] = "Vous devez vous connecter pour accéder au contenu."
      redirect_to new_session_path
    end
  end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  def index
  end

  def show
    @gossip = Gossip.find(params[:id])

  end

  def new
    @gossip = Gossip.new
  end


  def create
     @gossip = Gossip.new(title: params[:title],
       content: params[:content],  user: User.find(params[:user]))
       if @gossip.save
         flash[:success] = "The Gossip was successfuly created"
           redirect_to gossips_path
       else render 'new'
  end
end

def edit
    @gossip = Gossip.find(params[:id])
end

def update
    @gossip = Gossip.find(params[:id])
    gossip_params =  params.require(:gossip).permit(:title, :content, :user)
    if @gossip.update(gossip_params)
      flash[:success] = "The Gossip was successfuly updated"
    redirect_to gossips_path
  end
end

def destroy
  @gossip = Gossip.find(params[:id])
@gossip.destroy
redirect_to gossips_path
end


private

def gossip_params
    return params.require(:gossip).permit(:title, :content, :user)
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user_params = params.require(:user).permit(:email, :password, :username)
    @user = User.new(user_params)
    if @user.valid?

    else render 'new'

  end
end

  def update
  end

  def edit
  end

  def destroy
  end

  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
   <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
   <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
   <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
   <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet">
   <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <style>
       .navbar {
            background-color: #4a4e69;
            }

            .nav-link, .navbar-brand {
                color: #f2e9e4;
            }
            .btn-secondary, .btn-primary:hover {
            background-color: #cc8b79 !important;
            }
             btn:focus, .btn:active {
             outline: none !important;
             box-shadow: none !important;
            }
            .JumboHeaderImg {
            background-image: url("https://images.unsplash.com/photo-1531685250784-7569952593d2?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1567&q=80");
            background-size: cover;
            }


            /*comments CSS code*/
            body{margin-top:20px;}

            .comment-wrapper .panel-body {
                max-height:650px;
                overflow:auto;
            }

            .comment-wrapper .media-list .media img {
                width:64px;
                height:64px;
                border:2px solid #e5e7e8;
            }

            .comment-wrapper .media-list .media {
                border-bottom:1px dashed #efefef;
                margin-bottom:25px;
            }

</style>



  <nav class="navbar navbar-expand-lg">
  <a class="navbar-brand" href="#">The Gossip Project</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%=root_path %>">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=team_path %>">Team <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<%=contact_path %>">Contact us</a>
      </li>
        </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="<%=new_session_path %>">Login</a>
        </li>
      <li class="nav-item">
        <a class="btn btn-outline-light mr-sm-2" href="<%= new_user_path %>">Sign up</a>
      </li>
        </ul>
  </div>
</nav>

  </head>

  <body>
    <%= yield %>
  </body>
</html>